import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { blankState, executeCommand } from "../functions/domain/command_processor.mjs";
import { managerMonthlyReport } from "../functions/domain/canonical_selectors.mjs";

const manager={id:"manager",role:"owner",active:true};
const employee={id:"employee",role:"employee",active:true};
const run=(state,command,id,payload,actor=manager)=>executeCommand(state,command,{operationId:`approved-ops:${id}`,payload,actor,now:"2026-08-10T10:00:00.000Z"});
const opd={amountFils:100000,sourceAccount:"revenue",date:"2026-08-10",reason:"توزيع معتمد لصاحب المبنى"};

test("OPD01/06 valid owner distribution debits selected source and is ledger-backed",()=>{const s=blankState();s.balances.revenue=300000;const x=run(s,"createOwnerProfitDistribution","opd01",opd);assert.equal(x.state.balances.revenue,200000);assert.equal(x.state.ownerProfitDistributions.length,1);assert.equal(x.state.ledger[0].sourceType,"owner_profit_distribution");});
test("OPD02 employee denied",()=>assert.throws(()=>run(blankState(),"createOwnerProfitDistribution","opd02",opd,employee),/MANAGER_REQUIRED/));
test("OPD03 insufficient balance denied",()=>assert.throws(()=>run(blankState(),"createOwnerProfitDistribution","opd03",opd),/INSUFFICIENT_BALANCE/));
test("OPD04 non-positive denied",()=>assert.throws(()=>run(blankState(),"createOwnerProfitDistribution","opd04",{...opd,amountFils:0}),/AMOUNT_MUST_BE_POSITIVE/));
test("OPD05 retry exactly once",()=>{const s=blankState();s.balances.revenue=300000;const a=run(s,"createOwnerProfitDistribution","opd05",opd);const b=run(a.state,"createOwnerProfitDistribution","opd05",opd);assert.equal(b.replay,true);assert.equal(b.state.balances.revenue,200000);assert.equal(b.state.ownerProfitDistributions.length,1);});
test("OPD07 tenant metrics unchanged",()=>{const s=blankState();s.balances.revenue=300000;s.cycles.push({id:"c",reportingMonth:"2026_08",baseAmountFils:300000,dueDate:"2026-08-01",status:"open"});const before=managerMonthlyReport(s,"2026_08","2026-08-10").cards;const after=managerMonthlyReport(run(s,"createOwnerProfitDistribution","opd07",opd).state,"2026_08","2026-08-10").cards;assert.deepEqual(after,before);});
test("OPD08/09 reversal restores same account once",()=>{const s=blankState();s.balances.revenue=300000;const a=run(s,"createOwnerProfitDistribution","opd08",opd);const id=a.result.ownerProfitDistributionId;const b=run(a.state,"reverseOwnerProfitDistribution","opd08r",{ownerProfitDistributionId:id,reason:"تصحيح"});assert.equal(b.state.balances.revenue,300000);assert.throws(()=>run(b.state,"reverseOwnerProfitDistribution","opd09",{ownerProfitDistributionId:id,reason:"مرة أخرى"}),/ALREADY_REVERSED/);});
test("OPD10 direct Firestore write denied by Rules",()=>assert.match(fs.readFileSync("firestore-v11.rules","utf8"),/match \/ownerProfitDistributions\/\{id\}[\s\S]*?allow write: if false/));
test("OPD11 report classification separate from expenses",()=>{const s=blankState();s.balances.revenue=300000;const report=managerMonthlyReport(run(s,"createOwnerProfitDistribution","opd11",opd).state,"2026_08","2026-08-10");assert.equal(report.accounting.ownerProfitDistributions.length,1);assert.equal(report.accounting.expenses.length,0);});

const obligation=()=>({id:"installment-obligation:1",amountFils:10000000,dueDate:"2026-09-30",description:"قسط",reference:"Q1",effectiveMonth:"2026_09",version:1});
test("IO01/02 amount and due date can be corrected",()=>{const s=blankState();s.installmentObligations.push(obligation());const x=run(s,"adjustInstallmentObligation","io01",{obligationId:obligation().id,expectedVersion:1,amountFils:11000000,dueDate:"2026-10-01",reason:"تصحيح"});assert.equal(x.state.installmentObligations[0].amountFils,11000000);assert.equal(x.state.installmentObligations[0].dueDate,"2026-10-01");});
test("IO03 reason mandatory",()=>{const s=blankState();s.installmentObligations.push(obligation());assert.throws(()=>run(s,"adjustInstallmentObligation","io03",{obligationId:obligation().id,expectedVersion:1,amountFils:11000000}),/REASON_REQUIRED/);});
test("IO04 employee denied",()=>{const s=blankState();s.installmentObligations.push(obligation());assert.throws(()=>run(s,"adjustInstallmentObligation","io04",{obligationId:obligation().id,expectedVersion:1,amountFils:11000000,reason:"تصحيح"},employee),/MANAGER_REQUIRED/);});
test("IO05 stale version denied",()=>{const s=blankState();s.installmentObligations.push(obligation());assert.throws(()=>run(s,"adjustInstallmentObligation","io05",{obligationId:obligation().id,expectedVersion:0,amountFils:11000000,reason:"تصحيح"}),/STALE_INSTALLMENT_OBLIGATION/);});
test("IO06-IO10 payments stay immutable, remaining recalculates, balance does not move",()=>{const s=blankState();s.balances.revenue=9000000;s.installmentObligations.push(obligation());s.installments.push({id:"installment:p1",obligationId:obligation().id,account:"revenue",amountFils:4000000,status:"paid"});const before=structuredClone(s.installments);const x=run(s,"adjustInstallmentObligation","io06",{obligationId:obligation().id,expectedVersion:1,amountFils:11000000,reason:"تصحيح أصل الالتزام"});assert.deepEqual(x.state.installments,before);assert.equal(x.result.remainingFils,7000000);assert.equal(x.state.balances.revenue,9000000);assert.equal(x.state.ledger.length,0);assert.throws(()=>run(s,"adjustInstallmentObligation","io10",{obligationId:obligation().id,expectedVersion:1,amountFils:3000000,reason:"قيمة غير منطقية"}),/BELOW_PAID/);});

const lc={legacyRecordReference:"months/2026_07#profits[0]",legacyRecordHash:"abc",correctionType:"compensating_debit",amountFils:50000,account:"revenue",direction:"decrease",reason:"تصحيح موثق",confidence:"UNVERIFIED",managerAsserted:true,effectiveMonth:"2026_07"};
test("LC01/02 original reference remains immutable and separate correction event is created",()=>{const s=blankState();s.balances.revenue=100000;const legacy={amount:500};const before=structuredClone(legacy);const x=run(s,"createLegacyFinancialCorrection","lc01",lc);assert.deepEqual(legacy,before);assert.equal(x.state.legacyFinancialCorrections.length,1);assert.equal(x.state.legacyFinancialCorrections[0].legacyRecordReference,lc.legacyRecordReference);});
test("LC03 reason mandatory",()=>{const s=blankState();s.balances.revenue=100000;assert.throws(()=>run(s,"createLegacyFinancialCorrection","lc03",{...lc,reason:""}),/REASON_REQUIRED/);});
test("LC04 manager only",()=>assert.throws(()=>run(blankState(),"createLegacyFinancialCorrection","lc04",lc,employee),/MANAGER_REQUIRED/));
test("LC05/06 lineage is not invented and manager assertion is explicit",()=>{const s=blankState();s.balances.revenue=100000;const e=run(s,"createLegacyFinancialCorrection","lc05",{...lc,legacyRecordHash:null}).state.legacyFinancialCorrections[0];assert.equal(e.sourceClassification,"MANAGER_ASSERTED");assert.equal(e.legacyRecordHash,null);assert.equal(e.historicalConfidencePreserved,true);});
test("LC07 only declared account/effect changes",()=>{const s=blankState();s.balances={company:200000,revenue:100000,deduction:300000};const x=run(s,"createLegacyFinancialCorrection","lc07",lc);assert.deepEqual(x.state.balances,{company:200000,revenue:50000,deduction:300000});});
test("LC08 retry exactly once",()=>{const s=blankState();s.balances.revenue=100000;const a=run(s,"createLegacyFinancialCorrection","lc08",lc);const b=run(a.state,"createLegacyFinancialCorrection","lc08",lc);assert.equal(b.replay,true);assert.equal(b.state.balances.revenue,50000);assert.equal(b.state.legacyFinancialCorrections.length,1);});
test("LC09 direct correction/legacy overwrite paths denied",()=>{const rules=fs.readFileSync("firestore-v11.rules","utf8");assert.match(rules,/match \/legacyFinancialCorrections\/\{id\}[\s\S]*?allow write: if false/);});
test("LC10/11 report is separate and historical confidence preserved",()=>{const s=blankState();s.balances.revenue=100000;const report=managerMonthlyReport(run(s,"createLegacyFinancialCorrection","lc10",lc).state,"2026_07","2026-08-10");assert.equal(report.accounting.legacyFinancialCorrections.length,1);assert.equal(report.accounting.legacyFinancialCorrections[0].confidence,"UNVERIFIED");});
test("LC12 command never bulk-writes legacy documents",()=>{const source=fs.readFileSync("functions/domain/command_processor.mjs","utf8");const body=source.slice(source.indexOf("function createLegacyFinancialCorrection"),source.indexOf("function adjustBalance"));assert.doesNotMatch(body,/months|requests|bankPayments/);});
