import test from "node:test";
import assert from "node:assert/strict";
import { blankState, executeCommand } from "../functions/domain/command_processor.mjs";
import { reconstructionCompletenessAudit } from "../functions/domain/reconstruction.mjs";
import { monthlyOperationalProjection } from "../functions/domain/canonical_selectors.mjs";

const manager={id:"manager",uid:"manager-uid",role:"manager",active:true};
const employee={id:"employee",uid:"employee-uid",role:"employee",active:true};
const month="2031_04", date="2031-04-12", sourceHash="a".repeat(64);
const base=()=>{const s=blankState();s.financialTruthVersion=3;s.cycles=[{id:"cycle:rebuild:1",tenancyId:"tenant:1",tenantId:"tenant:1",unitId:"unit:1",reportingMonth:month,dueDate:"2031-04-01",baseAmountFils:500000,status:"open",financialVersion:0}];s.openingBalances={company:1000000,revenue:0,deduction:0};s.balances=structuredClone(s.openingBalances);return s;};
const run=(s,command,id,payload,actor=employee,now="2031-05-01T10:00:00Z")=>executeCommand(s,command,{operationId:id,payload,actor,now});
const obligation={obligationId:"obligation:rebuild:1",cycleId:"cycle:rebuild:1",unitId:"unit:1",partitionId:"1",contractualAmountFils:500000,sourceReference:"synthetic-contract",sourceRecordHash:"b".repeat(64),sourceTenantIdentity:"tenant:1",sourceDueDate:"2031-04-01"};
const plan=(s)=>{s=run(s,"createReconstructionPlan","op:rebuild:plan",{monthKey:month,legacySnapshotHash:sourceHash,structuralSourceHash:"b".repeat(64),reviewedObligations:[obligation]},manager).state;s=run(s,"confirmReconstructionStructure","op:confirm:tenant",{reconstructionPlanId:"reconstruction:op:rebuild:plan",obligationId:obligation.obligationId,confirmationType:"tenant_identity",confirmedValue:"tenant:1",confirmationBasis:"synthetic-contract"}).state;return run(s,"confirmReconstructionStructure","op:confirm:due",{reconstructionPlanId:"reconstruction:op:rebuild:plan",obligationId:obligation.obligationId,confirmationType:"due_date",confirmedValue:"2031-04-01",confirmationBasis:"synthetic-contract"}).state;};
const meta=(ref)=>({reconstructionPlanId:"reconstruction:op:rebuild:plan",reconstructionSourceReference:ref});

test("AR01 manager creates an inactive evidence-separated plan",()=>{const s=plan(base());assert.equal(s.reconstructionPlans[0].status,"DRAFT");assert.equal(s.monthAuthorities[0].legacyProjectionEffect,"evidence_only_zero");assert.equal(s.monthAuthorities[0].activated,false)});
test("AR02 untagged financial entry is rejected inside reconstruction boundary",()=>assert.throws(()=>run(plan(base()),"createCashReceipt","op:untagged",{cycleId:"cycle:rebuild:1",amountFils:10000,paymentDate:date}),/RECONSTRUCTION_PLAN_REQUIRED/));
test("AR03 reconstructed cash retains effective and reconstructed timestamps",()=>{const out=run(plan(base()),"createCashReceipt","op:cash",{cycleId:"cycle:rebuild:1",amountFils:10000,paymentDate:date,...meta("receipt-1")});const e=out.state.collectionEvents[0];assert.equal(e.effectiveAt,date);assert.equal(e.originalEffectiveDate,date);assert.equal(e.reconstructedAt,"2031-05-01T10:00:00Z");assert.equal(e.reconstructionSourceReference,"receipt-1")});
test("AR04 retry cannot duplicate reconstructed collection",()=>{let out=run(plan(base()),"createCashReceipt","op:cash",{cycleId:"cycle:rebuild:1",amountFils:10000,paymentDate:date,...meta("receipt-1")});out=run(out.state,"createCashReceipt","op:cash",{cycleId:"cycle:rebuild:1",amountFils:10000,paymentDate:date,...meta("receipt-1")});assert.equal(out.replay,true);assert.equal(out.state.collectionEvents.length,1)});
test("AR05 bank approval remains required and inherits reconstruction lineage",()=>{let s=run(plan(base()),"createBankPayment","op:bank:q",{cycleId:"cycle:rebuild:1",amountFils:20000,paymentDate:date,...meta("bank-slip-1")}).state;assert.equal(s.paymentIntents[0].status,"pending");s=run(s,"approveBankPayment","op:bank:a",{paymentId:"pay:op:bank:q"},manager).state;assert.equal(s.collectionEvents[0].reconstructionPlanId,"reconstruction:op:rebuild:plan");assert.equal(s.collectionEvents[0].reconstructionSourceReference,"bank-slip-1")});
test("AR06 reconstructed deposit uses cash-lot lineage and manager approval",()=>{let s=run(plan(base()),"createCashReceipt","op:cash",{cycleId:"cycle:rebuild:1",amountFils:30000,paymentDate:date,...meta("receipt-1")}).state;s=run(s,"createDepositRequest","op:dep:q",{amountFils:30000,depositDate:date,allocations:[{cashLotId:"lot:op:cash",amountFils:30000}],...meta("deposit-slip-1")}).state;assert.equal(s.depositRequests[0].status,"pending");s=run(s,"approveDeposit","op:dep:a",{depositRequestId:"dep:op:dep:q"},manager).state;assert.equal(s.cashMovements[0].reconstructionPlanId,"reconstruction:op:rebuild:plan");assert.equal(s.collectionEvents.length,1)});
test("AR07 expense preserves employee request and manager approval",()=>{let s=run(plan(base()),"requestExpense","op:exp:q",{amountFils:12000,reason:"synthetic repair",monthKey:month,...meta("expense-invoice-1")}).state;assert.equal(s.expenses[0].status,"pending");s=run(s,"approveExpense","op:exp:a",{expenseId:"expense:op:exp:q",account:"company"},manager).state;assert.equal(s.expenses[0].status,"active");assert.equal(s.expenses[0].reconstructionSourceReference,"expense-invoice-1")});
test("AR08 confirmed handover changes holder but preserves reconstruction lineage",()=>{let s=run(plan(base()),"createCashReceipt","op:cash",{cycleId:"cycle:rebuild:1",amountFils:30000,paymentDate:date,...meta("receipt-1")}).state;s=run(s,"createCustodyTransfer","op:xfer:q",{to:"employee-b",amountFils:10000,allocations:[{cashLotId:"lot:op:cash",amountFils:10000}],monthKey:month,...meta("handover-note-1")}).state;s=run(s,"confirmCustodyTransfer","op:xfer:a",{transferId:"xfer:op:xfer:q"},{id:"employee-b",uid:"b",role:"employee",active:true}).state;assert.equal(s.custodyTransfers[0].status,"confirmed");assert.ok(s.cashMovements.every(x=>x.reconstructionPlanId==="reconstruction:op:rebuild:plan"))});
test("AR09 completeness audit blocks pending approvals and unresolved overpayments",()=>{let s=run(plan(base()),"createBankPayment","op:bank:q",{cycleId:"cycle:rebuild:1",amountFils:20000,paymentDate:date,...meta("bank-slip-1")}).state;const a=reconstructionCompletenessAudit(s,"reconstruction:op:rebuild:plan");assert.equal(a.complete,false);assert.ok(a.blockers.some(x=>x.startsWith("BANK_APPROVAL_PENDING")))});
test("AR10 activation is blocked when Legacy opening would also project",()=>{let s=plan(base());s.legacyOpeningStates=[{id:"legacy",monthKey:month,kind:"LEGACY_OPENING_STATE",batchStatus:"ACTIVE",targetFils:1}];assert.throws(()=>run(s,"activateReconstructionPlan","op:activate",{reconstructionPlanId:"reconstruction:op:rebuild:plan"},manager),/LEGACY_OPENING_WOULD_DOUBLE_COUNT/)});
test("AR11 clean reconstruction can activate locally only after controlled prerequisites and audit pass",()=>{let s=run(plan(base()),"createCashReceipt","op:cash",{cycleId:"cycle:rebuild:1",amountFils:30000,paymentDate:date,...meta("receipt-1")}).state;s=run(s,"createDepositRequest","op:dep:q",{amountFils:30000,depositDate:date,allocations:[{cashLotId:"lot:op:cash",amountFils:30000}],...meta("deposit-slip-1")}).state;s=run(s,"approveDeposit","op:dep:a",{depositRequestId:"dep:op:dep:q"},manager).state;Object.assign(s.reconstructionPlans[0],{preActivationApproved:true,freezeVerified:true,finalSourceHash:"c".repeat(64)});const check=reconstructionCompletenessAudit(s,"reconstruction:op:rebuild:plan");assert.equal(check.complete,true);s=run(s,"activateReconstructionPlan","op:activate",{reconstructionPlanId:"reconstruction:op:rebuild:plan"},manager).state;assert.equal(s.monthAuthorities[0].status,"ACTIVE")});
test("AR12 active reconstruction authority excludes Legacy opening projection",()=>{const s=base();s.monthAuthorities=[{id:month,monthKey:month,status:"ACTIVE",authority:"CANONICAL_RECONSTRUCTION",legacyProjectionEffect:"evidence_only_zero"}];s.legacyOpeningStates=[{id:"legacy",monthKey:month,kind:"LEGACY_OPENING_STATE",batchStatus:"ACTIVE",targetFils:999999}];assert.equal(monthlyOperationalProjection(s,month,date).cards.targetFils,500000)});
test("AR13 draft plan can roll back by cancellation before activation",()=>{const s=run(plan(base()),"cancelReconstructionPlan","op:cancel",{reconstructionPlanId:"reconstruction:op:rebuild:plan"},manager).state;assert.equal(s.reconstructionPlans[0].status,"CANCELLED");assert.equal(s.monthAuthorities[0].activated,false)});
