import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import crypto from "node:crypto";
import { blankState, executeCommand } from "../functions/domain/command_processor.mjs";
import { assertCanonicalCommandAllowed, CONTROL_STATES } from "../functions/domain/canonical_control.mjs";
import { monthlyOperationalProjection } from "../functions/domain/canonical_selectors.mjs";

const build="qama-phase3c-canonical-events-2026-08-12.3-clean-august-start",month="2026_7",planId="reconstruction:august";
const owner={id:"saeed",role:"owner",active:true},employee={id:"employee",role:"employee",active:true};
const seed=()=>{const s=blankState();s.canonicalControl={state:"ACTIVATION_REVIEW",version:7};s.financialTruthVersion=2;s.cleanStartInventory={properties:1,units:21,rentableSpaces:94,tenants:0,tenancies:0};s.balances={company:49175400,revenue:7086395,deduction:9117248};s.openingBalances=structuredClone(s.balances);s.reconstructionPlans=[{id:planId,monthKey:month,status:"DRAFT",reviewedObligations:[{obligationId:"unknown:1",structuralStatus:"NEEDS_TENANT_CONFIRMATION",planItemStatus:"REVIEWED"}]}];s.monthAuthorities=[{id:month,monthKey:month,status:"STAGED",authority:"CANONICAL_RECONSTRUCTION",reconstructionPlanId:planId,legacyProjectionEffect:"evidence_only_zero",activated:false}];s.legacyOpeningStates=[{id:"legacy:august",monthKey:month,kind:"LEGACY_OPENING_STATE",batchStatus:"ACTIVE",targetFils:999999,collectedFils:888888}];return s;};
const payload={reconstructionPlanId:planId,reason:"Owner abandoned historical August reconstruction and authorized canonical clean entry from zero",expectedBuildId:build};
const run=(state,id="clean:start:001",actor=owner)=>executeCommand(state,"abandonReconstructionAndActivate",{operationId:id,payload,actor,now:"2026-08-12T00:00:00.000Z"});

test("CS01 owner decision abandons unresolved plan and activates clean start",()=>{const out=run(seed()),s=out.state;assert.equal(s.reconstructionPlans[0].status,"ABANDONED");assert.equal(s.reconstructionPlans[0].reviewedObligations[0].historicalException,undefined);assert.equal(s.monthAuthorities[0].authority,"CANONICAL_CLEAN_START");assert.equal(s.monthAuthorities[0].status,"ACTIVE");assert.equal(s.canonicalControl.state,"CANONICAL_ACTIVE");assert.equal(s.financialTruthVersion,3);});
test("CS02 decision creates no canonical August entity or financial event",()=>{const before=seed(),after=run(before).state;for(const key of ["cycles","allocations","paymentIntents","collectionEvents","cashLots","cashMovements","depositRequests","custodyTransfers","expenses","ledger","refunds","installments"])assert.equal(after[key].length,0);assert.deepEqual(after.balances,before.balances);});
test("CS03 active clean-start authority suppresses every Legacy opening projection",()=>{const s=run(seed()).state,p=monthlyOperationalProjection(s,month,"2026-08-12");for(const value of Object.values(p.cards))assert.equal(Number(value||0),0);assert.equal(p.openingState,null);});
test("CS04 employee cannot make owner abandonment decision",()=>{assert.throws(()=>run(seed(),"clean:start:employee",employee),/MANAGER_REQUIRED/);assert.throws(()=>assertCanonicalCommandAllowed({control:{state:CONTROL_STATES.ACTIVATION_REVIEW,version:1},command:"abandonReconstructionAndActivate",payload,state:seed(),actor:employee}),/MANAGER_REQUIRED/);});
test("CS05 command is available only in activation review",()=>{for(const state of [CONTROL_STATES.RECONSTRUCTION_ALLOWED,CONTROL_STATES.CANONICAL_ACTIVE,CONTROL_STATES.MAINTENANCE_LOCKED])assert.throws(()=>assertCanonicalCommandAllowed({control:{state,version:1},command:"abandonReconstructionAndActivate",payload,state:seed(),actor:owner}),/ACTIVATION_GATE_CLOSED|CANONICAL_WRITES_DENIED/);assert.doesNotThrow(()=>assertCanonicalCommandAllowed({control:{state:CONTROL_STATES.ACTIVATION_REVIEW,version:1},command:"abandonReconstructionAndActivate",payload,state:seed(),actor:owner}));});
test("CS06 any canonical August cycle or financial record blocks clean start",()=>{const cycle=seed();cycle.cycles=[{id:"cycle:existing",reportingMonth:month,baseAmountFils:1,dueDate:"2026-08-01",status:"open"}];assert.throws(()=>run(cycle),/CLEAN_START_CANONICAL_MONTH_NOT_EMPTY/);const money=seed();money.collectionEvents=[{id:"collection:existing",collectionMonth:month}];assert.throws(()=>run(money),/CLEAN_START_CANONICAL_MONTH_NOT_EMPTY/);});
test("CS07 missing structure or existing occupancy blocks clean start",()=>{const missing=seed();missing.cleanStartInventory.rentableSpaces=0;assert.throws(()=>run(missing),/CANONICAL_STRUCTURE_REQUIRED/);const occupied=seed();occupied.cleanStartInventory.tenants=1;assert.throws(()=>run(occupied),/CLEAN_START_OCCUPANCY_NOT_EMPTY/);});
test("CS08 reason and exact build identity are mandatory",()=>{const noReason={...payload,reason:""};assert.throws(()=>executeCommand(seed(),"abandonReconstructionAndActivate",{operationId:"clean:no-reason",payload:noReason,actor:owner}),/OWNER_ABANDONMENT_REASON_REQUIRED/);const noBuild={...payload,expectedBuildId:""};assert.throws(()=>executeCommand(seed(),"abandonReconstructionAndActivate",{operationId:"clean:no-build",payload:noBuild,actor:owner}),/EXPECTED_BUILD_ID_REQUIRED/);});
test("CS09 replay is exactly once and audit is immutable",()=>{let out=run(seed());out=run(out.state);assert.equal(out.replay,true);assert.equal(out.state.audit.filter(x=>x.action==="reconstruction_abandoned_clean_start_activated").length,1);assert.equal(out.state.reconstructionPlans[0].abandonmentOperationId,"clean:start:001");});
test("CS10 canonical-only UI and structural bootstrap remain intact",()=>{const html=fs.readFileSync(new URL("../public/index.html",import.meta.url),"utf8");assert.match(html,/canonicalOperationalWorkspaceActive\(\)/);assert.match(html,/renderCanonicalOperationalShell\(\)/);const after=fs.readFileSync(new URL("../functions/domain/legacy_structural_bootstrap.mjs",import.meta.url));const hash=crypto.createHash("sha256").update(after).digest("hex");assert.equal(hash,"43d8e9313b67811bb841ed98479e18b02c88389761ddd0356cb22c43517751f8");});
