import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { blankState, executeCommand } from "../functions/domain/command_processor.mjs";
import { cycleProjection } from "../functions/domain/financial_engine.mjs";

const manager={id:"manager",role:"manager",active:true}, employee={id:"employee",role:"employee",active:true};
const hash="d".repeat(64);
const run=(s,c,id,p,a=manager)=>executeCommand(s,c,{operationId:id,payload:p,actor:a,now:"2034-01-02T03:04:05Z"});
const item=(n,month="2034_01")=>({obligationId:`obligation:${month}:${n}`,cycleId:`cycle:${month}:${n}`,unitId:`unit:${n}`,partitionId:String(n),contractualAmountFils:100000+n,sourceReference:`contract:${month}:${n}`,sourceRecordHash:hash});
function plan(month,items=[]){return run(blankState(),"createReconstructionPlan",`plan:${month}`,{monthKey:month,legacySnapshotHash:hash,reviewedObligations:items}).state;}
function confirm(s,planId,o,n){s=run(s,"confirmReconstructionStructure",`confirm:tenant:${n}`,{reconstructionPlanId:planId,obligationId:o.obligationId,confirmationType:"tenant_identity",confirmedValue:`Tenant ${n}`,confirmationBasis:`record:${n}`},employee).state;s=run(s,"confirmReconstructionStructure",`confirm:due:${n}`,{reconstructionPlanId:planId,obligationId:o.obligationId,confirmationType:"due_date",confirmedValue:"2034-01-15",confirmationBasis:`record:${n}`},employee).state;return run(s,"linkReconstructionObligationStructure",`link:${n}`,{reconstructionPlanId:planId,obligationId:o.obligationId,propertyId:"property:test",unitId:`unit:${n}`,spaceId:`space:${n}`,tenantId:`tenant:${n}`,tenancyId:`tenancy:${n}`,sourceReference:`registry:${n}`}).state;}

test("DC01 zero-obligation plan is safe and materializes nothing",()=>{let s=plan("2034_01");const id=s.reconstructionPlans[0].id;const out=run(s,"materializeReconstructionCycles","mat:zero",{reconstructionPlanId:id});assert.deepEqual(out.result.materialized,[]);assert.equal(out.result.totalPlanObligations,0);assert.equal(out.state.cycles.length,0);});
test("DC02 one ready obligation materializes one canonical rental cycle",()=>{const o=item(1);let s=plan("2034_01",[o]);const id=s.reconstructionPlans[0].id;s=confirm(s,id,o,1);const out=run(s,"materializeReconstructionCycles","mat:one",{reconstructionPlanId:id});assert.equal(out.state.cycles.length,1);assert.equal(out.state.cycles[0].origin,"reconstruction");assert.equal(out.state.ledger.length,0);});
test("DC03 multiple ready obligations enumerate dynamically",()=>{const os=[item(1),item(2),item(3)];let s=plan("2034_01",os),id=s.reconstructionPlans[0].id;os.forEach((o,i)=>{s=confirm(s,id,o,i+1)});const out=run(s,"materializeReconstructionCycles","mat:many",{reconstructionPlanId:id});assert.equal(out.result.materialized.length,3);assert.equal(out.result.totalPlanObligations,3);});
test("DC04 mixed ready and incomplete obligations are independent",()=>{const os=[item(1),item(2)];let s=plan("2034_01",os),id=s.reconstructionPlans[0].id;s=confirm(s,id,os[0],1);const out=run(s,"materializeReconstructionCycles","mat:mixed",{reconstructionPlanId:id});assert.equal(out.result.materialized.length,1);assert.deepEqual(out.result.blocked.map(x=>x.obligationId),[os[1].obligationId]);});
test("DC05 a newly added DRAFT-plan obligation can later confirm and materialize",()=>{let s=plan("2034_01"),id=s.reconstructionPlans[0].id,o=item(9);s=run(s,"addReconstructionObligation","add:obligation:9",{reconstructionPlanId:id,obligation:o}).state;s=confirm(s,id,o,9);const out=run(s,"materializeReconstructionCycles","mat:added",{reconstructionPlanId:id});assert.equal(out.state.cycles[0].id,o.cycleId);});
test("DC06 cancelled unmaterialized obligation cannot create an active cycle",()=>{const o=item(4);let s=plan("2034_01",[o]),id=s.reconstructionPlans[0].id;s=run(s,"cancelReconstructionObligation","cancel:4",{reconstructionPlanId:id,obligationId:o.obligationId,reason:"contract cancelled"}).state;const out=run(s,"materializeReconstructionCycles","mat:cancelled",{reconstructionPlanId:id});assert.equal(out.state.cycles.length,0);assert.equal(out.result.skipped[0].reason,"CANCELLED");});
test("DC07 re-materializing a processed dynamic plan is idempotent",()=>{const o=item(5);let s=plan("2034_01",[o]),id=s.reconstructionPlans[0].id;s=confirm(s,id,o,5);s=run(s,"materializeReconstructionCycles","mat:first",{reconstructionPlanId:id}).state;const out=run(s,"materializeReconstructionCycles","mat:second",{reconstructionPlanId:id});assert.equal(out.state.cycles.length,1);assert.equal(out.result.skipped[0].reason,"ALREADY_MATERIALIZED");});
test("DC08 no fixed count or August identifier exists in production bridge logic",()=>{const source=fs.readFileSync(new URL("../functions/domain/command_processor.mjs",import.meta.url),"utf8");assert.doesNotMatch(source,/expect exactly|2026_7|74 obligations|\.length\s*[!=]==?\s*74/);});
test("DC09 a future-month plan uses the same engine",()=>{const o=item(1,"2042_11");let s=plan("2042_11",[o]),id=s.reconstructionPlans[0].id;s=confirm(s,id,o,"future");const out=run(s,"materializeReconstructionCycles","mat:future",{reconstructionPlanId:id});assert.equal(out.state.cycles[0].reportingMonth,"2042_11");});
test("DC10 normal post-cutover creation writes the same canonical cycle schema",()=>{const out=run(blankState(),"createRentalCycle","normal:1",{cycleId:"cycle:normal:1",tenancyId:"tenancy:1",tenantId:"tenant:1",unitId:"unit:1",contractualAmountFils:100500,reportingMonth:"2042_12",dueDate:"2042-12-10",sourceReference:"lease:1"});assert.equal(out.state.cycles[0].origin,"normal");assert.equal(out.state.cycles[0].baseAmountFils,100500);});
test("DC11 provenance metadata does not change financial semantics",()=>{const base={id:"a",tenancyId:"t",baseAmountFils:150000,reportingMonth:"2034_01",dueDate:"2034-01-15",status:"open",financialVersion:0};const s=blankState();assert.deepEqual(cycleProjection({...base,origin:"normal"},s),cycleProjection({...base,origin:"reconstruction",reconstructionPlanId:"p"},s));});
test("DC11B ready confirmation without canonical registry linkage remains blocked",()=>{const o=item(8);let s=plan("2034_01",[o]),id=s.reconstructionPlans[0].id;s=run(s,"confirmReconstructionStructure","confirm:tenant:unlinked",{reconstructionPlanId:id,obligationId:o.obligationId,confirmationType:"tenant_identity",confirmedValue:"Tenant",confirmationBasis:"record"},employee).state;s=run(s,"confirmReconstructionStructure","confirm:due:unlinked",{reconstructionPlanId:id,obligationId:o.obligationId,confirmationType:"due_date",confirmedValue:"2034-01-15",confirmationBasis:"record"},employee).state;const out=run(s,"materializeReconstructionCycles","mat:unlinked",{reconstructionPlanId:id});assert.equal(out.state.cycles.length,0);assert.equal(out.result.blocked[0].reason,"CANONICAL_STRUCTURE_LINK_REQUIRED");});
test("DC12 UI and read model use rentalCycles dynamically",()=>{for(const path of ["index.html","public/index.html"]){const html=fs.readFileSync(new URL(`../${path}`,import.meta.url),"utf8");assert.match(html,/collection\(db,"rentalCycles"\)/);assert.doesNotMatch(html,/collection\(db,"cycles"\)/);}const read=fs.readFileSync(new URL("../functions/canonical_read_model.mjs",import.meta.url),"utf8");assert.match(read,/rentalCycles:\s*state\.cycles/);});
