import test from "node:test";
import assert from "node:assert/strict";
import { blankState, executeCommand } from "../functions/domain/command_processor.mjs";
import { assertCanonicalCommandAllowed } from "../functions/domain/canonical_control.mjs";

const month="2031_04",hash="a".repeat(64),manager={id:"manager",role:"manager",active:true},employee={id:"employee",role:"employee",active:true};
const permit={state:"MAINTENANCE_LOCKED",version:3,structuralPreparation:{enabled:true,monthKey:month,version:1}};
const obligation={obligationId:"obl:1",cycleId:"cycle:1",unitId:"101",partitionId:"2",contractualAmountFils:125000,sourceReference:"contract:1",sourceRecordHash:"b".repeat(64),sourceTenantIdentity:null,sourceDueDate:null};
const run=(s,c,id,p,a=employee)=>executeCommand(s,c,{operationId:id,payload:p,actor:a,now:"2031-05-01T10:00:00Z"});
function staged(){let s=blankState();s=run(s,"createReconstructionPlan","op:plan",{monthKey:month,legacySnapshotHash:hash,structuralSourceHash:hash,reviewedObligations:[obligation]},manager).state;return s;}
const planId="reconstruction:op:plan";

test("PS01 explicit scoped permit allows only staged plan and structural confirmation while maintenance remains locked",()=>{assert.doesNotThrow(()=>assertCanonicalCommandAllowed({control:permit,command:"createReconstructionPlan",payload:{monthKey:month},state:blankState(),actor:manager}));for(const command of ["createCashReceipt","createDepositRequest","requestExpense","createCustodyTransfer","createBankInstallmentPayment","activateReconstructionPlan"])assert.throws(()=>assertCanonicalCommandAllowed({control:permit,command,payload:{monthKey:month},state:blankState(),actor:manager}),/CANONICAL_WRITES_DENIED/);assert.throws(()=>assertCanonicalCommandAllowed({control:{state:"MAINTENANCE_LOCKED",version:3},command:"createReconstructionPlan",payload:{monthKey:month},state:blankState(),actor:manager}),/CANONICAL_WRITES_DENIED/)});
test("PS02 plan is staged, non-active, evidence-separated, and progressively incomplete",()=>{const s=staged();const p=s.reconstructionPlans[0];assert.equal(p.status,"DRAFT");assert.equal(p.structuralReviewStatus,"PENDING");assert.equal(p.reviewedObligations[0].structuralStatus,"NEEDS_TENANT_AND_DUE_DATE_CONFIRMATION");assert.equal(s.monthAuthorities[0].activated,false);assert.equal(s.monthAuthorities[0].legacyProjectionEffect,"evidence_only_zero")});
test("PS03 tenant confirmation is auditable and has zero financial effect",()=>{const before=staged();const out=run(before,"confirmReconstructionStructure","op:tenant",{reconstructionPlanId:planId,obligationId:"obl:1",confirmationType:"tenant_identity",confirmedValue:"Tenant A",confirmationBasis:"signed contract"});const s=out.state,p=s.reconstructionPlans[0],o=p.reviewedObligations[0];assert.equal(o.confirmedTenantIdentity,"Tenant A");assert.equal(o.structuralStatus,"NEEDS_DUE_DATE_CONFIRMATION");assert.equal(p.structuralConfirmations[0].confirmedBy,"employee");assert.equal(p.structuralConfirmations[0].previousUnresolvedState,null);for(const k of ["collectionEvents","depositRequests","expenses","cashMovements","ledger"])assert.equal(s[k].length,0);assert.deepEqual(s.balances,before.balances)});
test("PS04 due-date confirmation completes only that obligation without changing amount or money",()=>{let s=staged();s=run(s,"confirmReconstructionStructure","op:tenant",{reconstructionPlanId:planId,obligationId:"obl:1",confirmationType:"tenant_identity",confirmedValue:"Tenant A",confirmationBasis:"signed contract"}).state;const out=run(s,"confirmReconstructionStructure","op:due",{reconstructionPlanId:planId,obligationId:"obl:1",confirmationType:"due_date",confirmedValue:"2031-04-03",confirmationBasis:"signed contract",contractualAmountFils:1});const o=out.state.reconstructionPlans[0].reviewedObligations[0];assert.equal(o.confirmedDueDate,"2031-04-03");assert.equal(o.structuralStatus,"READY_FOR_RECONSTRUCTION");assert.equal(o.contractualAmountFils,125000);assert.equal(out.state.reconstructionPlans[0].structuralReviewStatus,"APPROVED");assert.equal(out.state.ledger.length,0)});
test("PS05 unconfirmed obligation cannot accept reconstructed finance even after reconstruction gate opens",()=>{const s=staged();assert.throws(()=>assertCanonicalCommandAllowed({control:{state:"RECONSTRUCTION_ALLOWED",version:4},command:"createCashReceipt",payload:{reconstructionPlanId:planId,cycleId:"cycle:1"},state:s,actor:employee}),/OBLIGATION_STRUCTURAL_CONFIRMATION_REQUIRED/);assert.throws(()=>run(s,"createCashReceipt","op:cash",{cycleId:"cycle:1",amountFils:10000,paymentDate:"2031-04-03",reconstructionPlanId:planId,reconstructionSourceReference:"receipt:1"}),/OBLIGATION_STRUCTURAL_CONFIRMATION_REQUIRED/)});
test("PS06 confirmation retry is idempotent and conflicting second confirmation is rejected",()=>{let out=run(staged(),"confirmReconstructionStructure","op:tenant",{reconstructionPlanId:planId,obligationId:"obl:1",confirmationType:"tenant_identity",confirmedValue:"Tenant A",confirmationBasis:"signed contract"});out=run(out.state,"confirmReconstructionStructure","op:tenant",{reconstructionPlanId:planId,obligationId:"obl:1",confirmationType:"tenant_identity",confirmedValue:"Tenant A",confirmationBasis:"signed contract"});assert.equal(out.replay,true);assert.equal(out.state.reconstructionPlans[0].structuralConfirmations.length,1);assert.throws(()=>run(out.state,"confirmReconstructionStructure","op:tenant:other",{reconstructionPlanId:planId,obligationId:"obl:1",confirmationType:"tenant_identity",confirmedValue:"Tenant B",confirmationBasis:"other"}),/STRUCTURAL_CONFIRMATION_ALREADY_RECORDED/)});
test("PS07 activation remains blocked while any obligation confirmation is incomplete",()=>{const s=staged();assert.throws(()=>run(s,"activateReconstructionPlan","op:activate",{reconstructionPlanId:planId},manager),/STRUCTURAL_CONFIRMATIONS_INCOMPLETE/)});
