import assert from "node:assert/strict";
import { initializeApp as adminInit } from "firebase-admin/app";
import { getAuth as getAdminAuth } from "firebase-admin/auth";
import { getFirestore } from "firebase-admin/firestore";
import { initializeApp } from "firebase/app";
import { connectAuthEmulator, getAuth, signInWithCustomToken } from "firebase/auth";
import { connectFunctionsEmulator, getFunctions, httpsCallable } from "firebase/functions";

process.env.FIRESTORE_EMULATOR_HOST ||= "127.0.0.1:8080";
process.env.FIREBASE_AUTH_EMULATOR_HOST ||= "127.0.0.1:9099";
const projectId="qama-test", uid="staging_lock_owner";
const admin=adminInit({projectId},`staging-lock-${Date.now()}`),db=getFirestore(admin),authAdmin=getAdminAuth(admin);
try{await authAdmin.createUser({uid});}catch{}
await db.collection("users").doc(uid).set({userKey:"staging-owner",role:"owner",active:true});
await db.collection("config").doc("system").set({financialTruthVersion:3});
await db.collection("rentalCycles").doc("cycle:staging:1").set({id:"cycle:staging:1",tenancyId:"tenant",tenantId:"tenant",unitId:"unit",baseAmountFils:100000,reportingMonth:"2031_04",dueDate:"2031-04-01",status:"open",financialVersion:0});
for(const account of ["company","revenue","deduction"])await db.collection("accountBalances").doc(account).set({account,amountFils:account==="company"?500000:0,version:0});
const app=initializeApp({projectId,apiKey:"fake",appId:"staging-lock"},`staging-lock-client-${Date.now()}`);
const auth=getAuth(app);connectAuthEmulator(auth,"http://127.0.0.1:9099",{disableWarnings:true});await signInWithCustomToken(auth,await authAdmin.createCustomToken(uid));
const functions=getFunctions(app);connectFunctionsEmulator(functions,"127.0.0.1",5001);
const command=httpsCallable(functions,"financialCommand"),read=httpsCallable(functions,"canonicalReadModel");
const invoke=(commandName,operationId,payload={})=>command({command:commandName,operationId,payload});
let passed=0;
await assert.rejects(invoke("createInstallmentReserveTransfer","lock:missing:0001",{amountFils:10000,reason:"synthetic",effectiveDate:"2031-04-01"}));passed++;
let view=(await read({monthKey:"2031_04",asOfDate:"2031-04-01"})).data;assert.equal(view.canonicalControl.state,"MAINTENANCE_LOCKED");passed++;
await db.collection("config").doc("canonicalControl").set({state:"UNKNOWN",version:1});await assert.rejects(invoke("createCashReceipt","lock:unknown:0001",{cycleId:"cycle:staging:1",amountFils:10000,paymentDate:"2031-04-01"}));passed++;
await db.collection("config").doc("canonicalControl").set({state:"STAGED_READ_ONLY",version:1});await assert.rejects(invoke("createBankInstallmentPayment","lock:staged:0001",{amountFils:10000,reference:"synthetic",effectiveDate:"2031-04-01"}));passed++;
await db.collection("config").doc("canonicalControl").set({state:"MAINTENANCE_LOCKED",version:2,structuralPreparation:{enabled:true,monthKey:"2031_05",version:1}});
const reviewed={obligationId:"obligation:prep:1",cycleId:"cycle:prep:1",unitId:"unit",partitionId:"1",contractualAmountFils:100000,sourceReference:"synthetic-contract",sourceRecordHash:"b".repeat(64),sourceTenantIdentity:null,sourceDueDate:null};
const incomplete={obligationId:"obligation:prep:2",cycleId:"cycle:prep:2",unitId:"unit",partitionId:"2",contractualAmountFils:110000,sourceReference:"synthetic-contract-2",sourceRecordHash:"c".repeat(64),sourceTenantIdentity:null,sourceDueDate:null};
const created=await invoke("createReconstructionPlan","lock:prep:plan:0001",{monthKey:"2031_05",legacySnapshotHash:"a".repeat(64),structuralSourceHash:"b".repeat(64),reviewedObligations:[reviewed,incomplete]});const prepPlan=created.data.reconstructionPlanId;
await invoke("confirmReconstructionStructure","lock:prep:tenant:0001",{reconstructionPlanId:prepPlan,obligationId:reviewed.obligationId,confirmationType:"tenant_identity",confirmedValue:"Tenant",confirmationBasis:"synthetic-contract"});
await invoke("confirmReconstructionStructure","lock:prep:due:0001",{reconstructionPlanId:prepPlan,obligationId:reviewed.obligationId,confirmationType:"due_date",confirmedValue:"2031-05-03",confirmationBasis:"synthetic-contract"});
await db.collection("properties").doc("property:prep").set({id:"property:prep",status:"active"});await db.collection("units").doc("unit:prep").set({id:"unit:prep",propertyId:"property:prep",status:"active"});await db.collection("rentableSpaces").doc("space:prep").set({id:"space:prep",propertyId:"property:prep",unitId:"unit:prep",status:"active"});await db.collection("tenants").doc("tenant:prep").set({id:"tenant:prep",status:"active"});await db.collection("tenancies").doc("tenancy:prep").set({id:"tenancy:prep",propertyId:"property:prep",unitId:"unit:prep",spaceId:"space:prep",tenantId:"tenant:prep",status:"active"});
await invoke("linkReconstructionObligationStructure","lock:prep:link:0001",{reconstructionPlanId:prepPlan,obligationId:reviewed.obligationId,propertyId:"property:prep",unitId:"unit:prep",spaceId:"space:prep",tenantId:"tenant:prep",tenancyId:"tenancy:prep",sourceReference:"synthetic-registry"});
const materialized=await invoke("materializeReconstructionCycles","lock:prep:materialize:0001",{reconstructionPlanId:prepPlan});assert.equal(materialized.data.materialized.length,1);assert.equal(materialized.data.blocked.length,1);
const prepared=(await db.collection("reconstructionPlans").doc(prepPlan).get()).data();assert.equal(prepared.status,"DRAFT");assert.equal(prepared.reviewedObligations[0].structuralStatus,"READY_FOR_RECONSTRUCTION");assert.equal((await db.collection("rentalCycles").doc(reviewed.cycleId).get()).data().origin,"reconstruction");assert.equal((await db.collection("financialLedger").get()).size,0);assert.equal((await db.collection("collectionEvents").get()).size,0);passed++;
await assert.rejects(invoke("createCashReceipt","lock:prep:cash:0001",{cycleId:"cycle:prep:1",amountFils:10000,paymentDate:"2031-05-03",reconstructionPlanId:prepPlan,reconstructionSourceReference:"receipt"}));passed++;
await db.collection("config").doc("canonicalControl").set({state:"RECONSTRUCTION_ALLOWED",version:3});
await invoke("createCashReceipt","lock:prep:ready:cash:0001",{cycleId:"cycle:prep:1",amountFils:10000,paymentDate:"2031-05-03",reconstructionPlanId:prepPlan,reconstructionSourceReference:"receipt-ready"});assert.equal((await db.collection("collectionEvents").where("operationId","==","lock:prep:ready:cash:0001").get()).size,1);passed++;
await assert.rejects(invoke("createCashReceipt","lock:prep:blocked:cash:0001",{cycleId:"cycle:prep:2",amountFils:10000,paymentDate:"2031-05-03",reconstructionPlanId:prepPlan,reconstructionSourceReference:"receipt-blocked"}));passed++;
await db.collection("reconstructionPlans").doc("plan:staging").set({id:"plan:staging",monthKey:"2031_04",status:"DRAFT",structuralReviewStatus:"APPROVED",reviewedObligations:[{obligationId:"obligation:staging:1",cycleId:"cycle:staging:1",structuralStatus:"READY_FOR_RECONSTRUCTION"}],requiredStructuralConfirmations:[],structuralConfirmations:[],preActivationApproved:false,freezeVerified:false,finalSourceHash:null});
await db.collection("monthAuthorities").doc("2031_04").set({id:"2031_04",monthKey:"2031_04",status:"STAGED",reconstructionPlanId:"plan:staging",activated:false,legacyProjectionEffect:"evidence_only_zero"});
await db.collection("config").doc("canonicalControl").set({state:"RECONSTRUCTION_ALLOWED",version:2});
await invoke("createCashReceipt","lock:recon:cash:0001",{cycleId:"cycle:staging:1",amountFils:10000,paymentDate:"2031-04-01",reconstructionPlanId:"plan:staging",reconstructionSourceReference:"synthetic-source"});assert.equal((await db.collection("collectionEvents").where("operationId","==","lock:recon:cash:0001").get()).size,1);passed++;
await assert.rejects(invoke("createInstallmentReserveTransfer","lock:recon:reserve:0001",{amountFils:10000,reason:"synthetic",effectiveDate:"2031-04-01"}));passed++;
await assert.rejects(invoke("activateReconstructionPlan","lock:recon:activate:0001",{reconstructionPlanId:"plan:staging"}));passed++;
assert.equal((await db.collection("monthAuthorities").doc("2031_04").get()).data().activated,false);passed++;
await db.collection("config").doc("canonicalControl").set({state:"CANONICAL_ACTIVE",version:3});
const reserve={command:"createInstallmentReserveTransfer",operationId:"lock:active:reserve:0001",payload:{amountFils:10000,reason:"synthetic",effectiveDate:"2031-04-01"}};
const [a,b]=await Promise.all([command(reserve),command(reserve)]);assert.equal(a.data.amountFils,10000);assert.equal(b.data.amountFils,10000);assert.equal((await db.collection("balanceTransfers").where("operationId","==",reserve.operationId).get()).size,1);passed++;
for(const [collection,id] of [["tenancies","tenancy:prep"],["tenants","tenant:prep"],["rentableSpaces","space:prep"],["units","unit:prep"],["properties","property:prep"]])await db.collection(collection).doc(id).delete();
console.log(JSON.stringify({tests:passed,pass:passed,fail:0,missingConfigDenied:true,readModelAvailable:true,reconstructionNotActivated:true,idempotent:true}));
process.exit(0);
