import test from "node:test";
import assert from "node:assert/strict";
import { blankState, executeCommand } from "../functions/domain/command_processor.mjs";
import { custodyProjection, money } from "../functions/domain/financial_engine.mjs";
import { suggestCashAllocation } from "../functions/domain/cash_allocation.mjs";
import { employeeOperationalReport, managerMonthlyReport, reportExportModel } from "../functions/domain/canonical_selectors.mjs";

const emp={id:"employee:yahia",role:"employee",active:true};
const empB={id:"employee:nader",role:"employee",active:true};
const mgr={id:"manager:saeed",role:"owner",active:true};
const finance={id:"legacy:finance",role:"finance",active:true};
const ctx=(operationId,actor,payload,now="2026-07-30T12:00:00Z")=>({operationId,actor,payload,now});
const seed=()=>{const s=blankState();s.cycles.push({id:"cycle:tenant-a:1",tenancyId:"tenant-a",unitId:"unit:101:8",tenant:"Tenant A",baseAmountFils:money(3000),reportingMonth:"2026_07",dueDate:"2026-08-10",status:"open_not_due",financialVersion:0});s.openingBalances={company:0,revenue:0,deduction:0};return s;};
const go=(s,cmd,id,actor,payload,now)=>executeCommand(s,cmd,ctx(id,actor,payload,now)).state;

test("W01 employee journey remains tenant -> receive payment -> deposit request -> status",()=>{let s=seed();s=go(s,"createCashReceipt","op:w01:c",emp,{cycleId:s.cycles[0].id,amountFils:money(1000),paymentDate:"2026-07-30"});s=go(s,"createDepositRequest","op:w01:d",emp,{allocations:[{cashLotId:"lot:op:w01:c",amountFils:money(1000)}],depositDate:"2026-08-02"});assert.equal(s.depositRequests[0].status,"pending");assert.equal(custodyProjection(s).totalFils,money(1000));});
test("W02 manager journey remains pending request -> approve -> correct result",()=>{let s=seed();s=go(s,"createBankPayment","op:w02:b",emp,{cycleId:s.cycles[0].id,amountFils:money(500),paymentDate:"2026-07-30"});assert.equal(s.paymentIntents[0].status,"pending");s=go(s,"approveBankPayment","op:w02:a",mgr,{paymentId:"pay:op:w02:b"});assert.equal(s.paymentIntents[0].status,"approved");});
test("W03 custody journey still requires receiver confirmation",()=>{let s=seed();s=go(s,"createCashReceipt","op:w03:c",emp,{cycleId:s.cycles[0].id,amountFils:money(500),paymentDate:"2026-07-30"});s=go(s,"createCustodyTransfer","op:w03:t",emp,{to:empB.id,allocations:[{cashLotId:"lot:op:w03:c",amountFils:money(500)}]});assert.equal(custodyProjection(s).byHolder[emp.id],money(500));s=go(s,"confirmCustodyTransfer","op:w03:k",empB,{transferId:"xfer:op:w03:t"});assert.equal(custodyProjection(s).byHolder[empB.id],money(500));});
test("W04 expense journey remains employee request -> manager chooses account -> approve",()=>{let s=seed();s.balances.company=money(1000);s=go(s,"requestExpense","op:w04:q",emp,{amountFils:money(200),reason:"repair"});s=go(s,"approveExpense","op:w04:a",mgr,{expenseId:"expense:op:w04:q",account:"company"});assert.equal(s.balances.company,money(800));});
test("W05 eviction journey remains employee request -> manager review -> approve",()=>{let s=seed();s=go(s,"requestEviction","op:w05:q",emp,{cycleId:s.cycles[0].id,reason:"vacating"});s=go(s,"approveEvictionRequest","op:w05:a",mgr,{evictionId:"eviction:op:w05:q"});assert.equal(s.cycles[0].status,"cancelled_eviction");});
test("W06 daily journey remains booking/payment before occupancy -> manager refund",()=>{let s=blankState();s=go(s,"createDailyBooking","op:w06:b",emp,{tenancyId:"daily:t1",unitId:"unit:1",tenant:"Guest",amountFils:money(500),method:"cash",paymentDate:"2026-07-30"});assert.equal(s.dailyBookings[0].housingAllowed,true);s=go(s,"refundDailyBooking","op:w06:r",mgr,{bookingId:"booking:op:w06:b",reason:"cancelled"});assert.equal(s.dailyBookings[0].housingAllowed,false);});

test("ST01 stale eviction fixture is denied without weakening version enforcement",()=>{let s=seed();s=go(s,"requestEviction","op:st01:q",emp,{cycleId:s.cycles[0].id,reason:"vacating"});s=go(s,"createCashReceipt","op:st01:c",emp,{cycleId:s.cycles[0].id,amountFils:money(100),paymentDate:"2026-07-30"});assert.throws(()=>go(s,"approveEvictionRequest","op:st01:a",mgr,{evictionId:"eviction:op:st01:q"}),/STALE_EVICTION_REQUEST/);});
test("ST02 deposit approval after funds were consumed is denied",()=>{let s=seed();s=go(s,"createCashReceipt","op:st02:c",emp,{cycleId:s.cycles[0].id,amountFils:money(1000),paymentDate:"2026-07-30"});s=go(s,"createDepositRequest","op:st02:d",emp,{allocations:[{cashLotId:"lot:op:st02:c",amountFils:money(800)}],depositDate:"2026-08-02"});s=go(s,"refundPayment","op:st02:r",mgr,{allocationId:"alloc:op:st02:c",amountFils:money(300),source:"custody",cashLotId:"lot:op:st02:c"});assert.throws(()=>go(s,"approveDeposit","op:st02:a",mgr,{depositRequestId:"dep:op:st02:d"}),/STALE_CASH_ALLOCATION/);});
test("ST03 bank approval rechecks current remaining",()=>{let s=seed();s=go(s,"createBankPayment","op:st03:b",emp,{cycleId:s.cycles[0].id,amountFils:money(2000),paymentDate:"2026-07-30"});s=go(s,"createCashReceipt","op:st03:c",empB,{cycleId:s.cycles[0].id,amountFils:money(2000),paymentDate:"2026-07-30"});assert.throws(()=>go(s,"approveBankPayment","op:st03:a",mgr,{paymentId:"pay:op:st03:b"}),/OVERPAYMENT/);});
test("ST04 stale custody confirmation is denied",()=>{let s=seed();s=go(s,"createCashReceipt","op:st04:c",emp,{cycleId:s.cycles[0].id,amountFils:money(1000),paymentDate:"2026-07-30"});s=go(s,"createCustodyTransfer","op:st04:t",emp,{to:empB.id,allocations:[{cashLotId:"lot:op:st04:c",amountFils:money(800)}]});s=go(s,"refundPayment","op:st04:r",mgr,{allocationId:"alloc:op:st04:c",amountFils:money(300),source:"custody",cashLotId:"lot:op:st04:c"});assert.throws(()=>go(s,"confirmCustodyTransfer","op:st04:k",empB,{transferId:"xfer:op:st04:t"}),/STALE_CASH_ALLOCATION/);});

test("CA01 single full lot suggestion can be confirmed unchanged",()=>{let s=seed();s=go(s,"createCashReceipt","op:ca01:c",emp,{cycleId:s.cycles[0].id,amountFils:money(1000),paymentDate:"2026-07-30"});const suggestion=suggestCashAllocation(s,emp.id,money(1000));assert.equal(suggestion.fullyAllocated,true);s=go(s,"createDepositRequest","op:ca01:d",emp,{amountFils:money(1000),allocations:suggestion.allocations,depositDate:"2026-08-02"});assert.equal(s.depositRequests[0].allocationConfirmedBy,emp.id);});
test("CA02 single partial lot preserves remainder",()=>{let s=seed();s=go(s,"createCashReceipt","op:ca02:c",emp,{cycleId:s.cycles[0].id,amountFils:money(3000),paymentDate:"2026-07-30"});const a=suggestCashAllocation(s,emp.id,money(1000)).allocations;s=go(s,"createDepositRequest","op:ca02:d",emp,{amountFils:money(1000),allocations:a,depositDate:"2026-08-02"});s=go(s,"approveDeposit","op:ca02:a",mgr,{depositRequestId:"dep:op:ca02:d"});assert.equal(custodyProjection(s).totalFils,money(2000));});
test("CA03 multiple lots compose exact requested amount",()=>{let s=seed();s=go(s,"createCashReceipt","op:ca03:a",emp,{cycleId:s.cycles[0].id,amountFils:money(1000),paymentDate:"2026-07-28"});s.cycles[0].baseAmountFils=money(4000);s=go(s,"createCashReceipt","op:ca03:b",emp,{cycleId:s.cycles[0].id,amountFils:money(500),paymentDate:"2026-07-29"});s=go(s,"createCashReceipt","op:ca03:c",emp,{cycleId:s.cycles[0].id,amountFils:money(2000),paymentDate:"2026-07-30"});const x=suggestCashAllocation(s,emp.id,money(2000));assert.deepEqual(x.allocations.map(v=>v.amountFils),[money(1000),money(500),money(500)]);});
test("CA04 employee may manually change suggested allocation",()=>{let s=seed();s.cycles[0].baseAmountFils=money(3000);s=go(s,"createCashReceipt","op:ca04:a",emp,{cycleId:s.cycles[0].id,amountFils:money(1000),paymentDate:"2026-07-28"});s=go(s,"createCashReceipt","op:ca04:b",emp,{cycleId:s.cycles[0].id,amountFils:money(1000),paymentDate:"2026-07-29"});s=go(s,"createDepositRequest","op:ca04:d",emp,{amountFils:money(1000),allocations:[{cashLotId:"lot:op:ca04:b",amountFils:money(1000)}],depositDate:"2026-08-02"});assert.equal(s.depositRequests[0].allocations[0].cashLotId,"lot:op:ca04:b");});
test("CA05 allocation exceeding available amount is denied",()=>{let s=seed();s=go(s,"createCashReceipt","op:ca05:c",emp,{cycleId:s.cycles[0].id,amountFils:money(500),paymentDate:"2026-07-30"});assert.throws(()=>go(s,"createDepositRequest","op:ca05:d",emp,{amountFils:money(600),allocations:[{cashLotId:"lot:op:ca05:c",amountFils:money(600)}]}),/STALE_CASH_ALLOCATION/);});
test("CA06 holder changed before submit is denied",()=>{let s=seed();s=go(s,"createCashReceipt","op:ca06:c",emp,{cycleId:s.cycles[0].id,amountFils:money(500),paymentDate:"2026-07-30"});const suggestion=suggestCashAllocation(s,emp.id,money(500));s=go(s,"createCustodyTransfer","op:ca06:t",emp,{to:empB.id,amountFils:money(500),allocations:suggestion.allocations});s=go(s,"confirmCustodyTransfer","op:ca06:k",empB,{transferId:"xfer:op:ca06:t"});assert.throws(()=>go(s,"createDepositRequest","op:ca06:d",emp,{amountFils:money(500),allocations:suggestion.allocations}),/STALE_CASH_ALLOCATION/);});
test("CA07 holder changed before confirmation is denied",()=>{let s=seed();s=go(s,"createCashReceipt","op:ca07:c",emp,{cycleId:s.cycles[0].id,amountFils:money(1000),paymentDate:"2026-07-30"});s=go(s,"createCustodyTransfer","op:ca07:t",emp,{to:empB.id,amountFils:money(700),allocations:[{cashLotId:"lot:op:ca07:c",amountFils:money(700)}]});s=go(s,"refundPayment","op:ca07:r",mgr,{allocationId:"alloc:op:ca07:c",amountFils:money(400),source:"custody",cashLotId:"lot:op:ca07:c"});assert.throws(()=>go(s,"confirmCustodyTransfer","op:ca07:k",empB,{transferId:"xfer:op:ca07:t"}),/STALE_CASH_ALLOCATION/);});
test("CA08 same lot twice in one request is denied",()=>{let s=seed();s=go(s,"createCashReceipt","op:ca08:c",emp,{cycleId:s.cycles[0].id,amountFils:money(1000),paymentDate:"2026-07-30"});assert.throws(()=>go(s,"createDepositRequest","op:ca08:d",emp,{amountFils:money(1000),allocations:[{cashLotId:"lot:op:ca08:c",amountFils:money(500)},{cashLotId:"lot:op:ca08:c",amountFils:money(500)}]}),/DUPLICATE_CASH_LOT_ALLOCATION/);});
test("CA09 allocation total must equal amount entered first",()=>{let s=seed();s=go(s,"createCashReceipt","op:ca09:c",emp,{cycleId:s.cycles[0].id,amountFils:money(1000),paymentDate:"2026-07-30"});assert.throws(()=>go(s,"createDepositRequest","op:ca09:d",emp,{amountFils:money(800),allocations:[{cashLotId:"lot:op:ca09:c",amountFils:money(500)}]}),/CASH_ALLOCATION_TOTAL_MISMATCH/);});
test("CA10 partial remainder can be allocated later without duplicate use",()=>{let s=seed();s=go(s,"createCashReceipt","op:ca10:c",emp,{cycleId:s.cycles[0].id,amountFils:money(1000),paymentDate:"2026-07-30"});s=go(s,"createDepositRequest","op:ca10:d1",emp,{amountFils:money(400),allocations:[{cashLotId:"lot:op:ca10:c",amountFils:money(400)}]});s=go(s,"approveDeposit","op:ca10:a1",mgr,{depositRequestId:"dep:op:ca10:d1"});s=go(s,"createDepositRequest","op:ca10:d2",emp,{amountFils:money(600),allocations:[{cashLotId:"lot:op:ca10:c",amountFils:money(600)}]});s=go(s,"approveDeposit","op:ca10:a2",mgr,{depositRequestId:"dep:op:ca10:d2"});assert.equal(custodyProjection(s).totalFils,0);});
test("ST05 stale discount approval is denied after remaining changed",()=>{let s=seed();s=go(s,"requestDiscount","op:st05:q",emp,{cycleId:s.cycles[0].id,amountFils:money(2500),reason:"request"});s=go(s,"createCashReceipt","op:st05:c",emp,{cycleId:s.cycles[0].id,amountFils:money(1000),paymentDate:"2026-07-30"});assert.throws(()=>go(s,"approveDiscountRequest","op:st05:a",mgr,{discountId:"discount:op:st05:q"}),/STALE_DISCOUNT_REQUEST/);});
test("ST06 balance transfer reversal rechecks destination funds",()=>{let s=seed();s.balances.company=money(1000);s=go(s,"transferBalance","op:st06:t",mgr,{source:"company",destination:"revenue",amountFils:money(800),reason:"allocation"});s=go(s,"executeExpense","op:st06:e",mgr,{account:"revenue",amountFils:money(500),reason:"used"});assert.throws(()=>go(s,"reverseBalanceTransfer","op:st06:r",mgr,{transferId:"balxfer:op:st06:t"}),/INSUFFICIENT_BALANCE/);});
test("ST07 month close cannot be replayed against a changed month state",()=>{let s=seed();s=go(s,"closeMonth","op:st07:c",mgr,{monthKey:"2026_07"});assert.throws(()=>go(s,"closeMonth","op:st07:c2",mgr,{monthKey:"2026_07"}),/MONTH_NOT_OPEN/);});
test("ST08 payment correction is denied after the allocation was fully refunded",()=>{let s=seed();s=go(s,"createCashReceipt","op:st08:c",emp,{cycleId:s.cycles[0].id,amountFils:money(500),paymentDate:"2026-07-30"});s=go(s,"refundPayment","op:st08:r",mgr,{allocationId:"alloc:op:st08:c",amountFils:money(500),source:"custody",cashLotId:"lot:op:st08:c"});assert.throws(()=>go(s,"correctPayment","op:st08:x",mgr,{allocationId:"alloc:op:st08:c",paymentDate:"2026-08-01",reason:"stale correction"}),/STALE_PAYMENT_CORRECTION/);});
test("ST09 payment cancellation cannot execute twice",()=>{let s=seed();s=go(s,"createBankPayment","op:st09:b",emp,{cycleId:s.cycles[0].id,amountFils:money(500),paymentDate:"2026-07-30"});s=go(s,"cancelPayment","op:st09:c1",mgr,{paymentId:"pay:op:st09:b",reason:"cancelled"});assert.throws(()=>go(s,"cancelPayment","op:st09:c2",mgr,{paymentId:"pay:op:st09:b",reason:"again"}),/PAYMENT_ALREADY_CANCELLED/);});
test("ST10 expense approval cannot execute after request state changed",()=>{let s=seed();s.balances.company=money(1000);s=go(s,"requestExpense","op:st10:q",emp,{amountFils:money(200),reason:"repair"});s=go(s,"approveExpense","op:st10:a1",mgr,{expenseId:"expense:op:st10:q",account:"company"});assert.throws(()=>go(s,"approveExpense","op:st10:a2",mgr,{expenseId:"expense:op:st10:q",account:"company"}),/EXPENSE_NOT_PENDING/);});
test("ST11 refund rechecks refundable amount after another refund",()=>{let s=seed();s=go(s,"createCashReceipt","op:st11:c",emp,{cycleId:s.cycles[0].id,amountFils:money(500),paymentDate:"2026-07-30"});s=go(s,"refundPayment","op:st11:r1",mgr,{allocationId:"alloc:op:st11:c",amountFils:money(400),source:"custody",cashLotId:"lot:op:st11:c"});assert.throws(()=>go(s,"refundPayment","op:st11:r2",mgr,{allocationId:"alloc:op:st11:c",amountFils:money(200),source:"custody",cashLotId:"lot:op:st11:c"}),/REFUND_EXCEEDS_PAYMENT/);});
test("ST12 reopen requires the current month state and a reason",()=>{let s=seed();s=go(s,"closeMonth","op:st12:c",mgr,{monthKey:"2026_07"});assert.throws(()=>go(s,"reopenMonth","op:st12:r0",mgr,{monthKey:"2026_07",reason:""}),/REASON_REQUIRED/);s=go(s,"reopenMonth","op:st12:r1",mgr,{monthKey:"2026_07",reason:"approved correction"});assert.throws(()=>go(s,"reopenMonth","op:st12:r2",mgr,{monthKey:"2026_07",reason:"again"}),/MONTH_NOT_CLOSED/);});

test("R01 employee report excludes internal accounting; manager report includes it",()=>{const s=seed();const e=employeeOperationalReport(s,"2026_07","2026-07-01");const m=managerMonthlyReport(s,"2026_07","2026-07-01");assert.equal("accounting" in e,false);assert.equal("accounting" in m,true);assert.equal(reportExportModel(s,"2026_07","2026-07-01","employee").accounting,undefined);});
test("R02 finance legacy role is not granted new canonical command authority",()=>{assert.throws(()=>go(seed(),"createCashReceipt","op:r02",finance,{cycleId:"cycle:tenant-a:1",amountFils:money(100),paymentDate:"2026-07-30"}),/STAFF_REQUIRED/);});
