// Offline analysis of the pre-audit production backup. No network and no writes.
import fs from "node:fs/promises";
const src=JSON.parse(await fs.readFile(new URL("../backups/full-system-before-july-financial-audit-2026-08-09T2002-GST.json",import.meta.url),"utf8"));
function dec(v){if(!v)return undefined;if("stringValue"in v)return v.stringValue;if("integerValue"in v)return Number(v.integerValue);if("doubleValue"in v)return Number(v.doubleValue);if("booleanValue"in v)return v.booleanValue;if("nullValue"in v)return null;if("timestampValue"in v)return v.timestampValue;if("arrayValue"in v)return(v.arrayValue.values||[]).map(dec);if("mapValue"in v)return Object.fromEntries(Object.entries(v.mapValue.fields||{}).map(([k,x])=>[k,dec(x)]));}
const docs=Object.entries(src.documents).map(([path,d])=>({path,data:Object.fromEntries(Object.entries(d.fields||{}).map(([k,v])=>[k,dec(v)])),encodedBytes:Buffer.byteLength(JSON.stringify(d))}));
const req=docs.filter(x=>x.path.startsWith("requests/")).map(x=>x.data),months=docs.filter(x=>x.path.startsWith("months/"));
const by=(rows,key)=>Object.fromEntries([...new Set(rows.map(x=>String(x[key]??"MISSING")))].sort().map(v=>[v,rows.filter(x=>String(x[key]??"MISSING")===v).length]));
const collectionReq=req.filter(x=>["update_partition","update_full","add_daily","add_transaction","add_handover","confirm_handover"].includes(x.type));
const evidence={};
for(const x of collectionReq){const p=x.payload||{},f=p.fields||{},booking=p.booking||{},tx=p.transaction||{};const k=x.type;evidence[k]??={total:0,approved:0,hasCollectedBy:0,hasMethod:0,hasAmount:0,hasOriginal:0};const e=evidence[k];e.total++;if(x.status==="approved")e.approved++;if(f.collectedBy||booking.collectedBy||tx.collectedBy)e.hasCollectedBy++;if(f.collectionMethod||booking.paymentMethod||tx.method||tx.type)e.hasMethod++;if(Number(f.paid_amount||booking.total||tx.amount)>0)e.hasAmount++;if(p.originalFields)e.hasOriginal++;}
const monthEvidence=months.map(x=>{const d=x.data.data||x.data,items=[...(d.units||[]).flatMap(u=>u.partitions||[]),...(d.full||[])],logs=d.logs||[];return{month:x.path.slice(7),encodedBytes:x.encodedBytes,transactions:(d.transactions||[]).length,handovers:(d.handovers||[]).length,cashReceipts:(d.cashReceipts||[]).length,unitCollections:items.filter(i=>i.status==="collected"||Number(i.paid_amount)>0).length,unitCollectionsWithActor:items.filter(i=>(i.status==="collected"||Number(i.paid_amount)>0)&&i.collectedBy).length,unitCollectionsWithTime:items.filter(i=>(i.status==="collected"||Number(i.paid_amount)>0)&&i.collectedAt).length,structuredCollectionLogs:logs.filter(l=>["المدفوع","الحالة"].includes(l.field)).length,totalLogs:logs.length};});
console.log(JSON.stringify({backupExportedAt:src.exportedAt,documentCount:src.documentCount,requestTypes:by(req,"type"),requestStatuses:by(req,"status"),collectionRequestEvidence:evidence,monthEvidence,maxMonthEncodedBytes:Math.max(...monthEvidence.map(x=>x.encodedBytes)),conclusion:"Historical cash is not deterministically reconstructable when collection unit state lacks a matching immutable approved request/event and deposits use by as creator."},null,2));
